apiVersion: v1
kind: ConfigMap
metadata:
  name: sqrbot
data:
  # These configurations are injected as environment variables into the
  # sqrbot app container.
  API_LSST_CODES_PROFILE: "production"
  SQRBOTJR_REGISTRY: "http://localhost:8081"
  SQRBOTJR_BROKER: "localhost:9092"
  SQRBOTJR_KAFKA_PROTOCOL: "PLAINTEXT"
  SQRBOTJR_KAFKA_SASL: "PLAIN"
  # Schema registry subject configuration
  SQRBOTJR_SUBJECT_SUFFIX: ""
  SQRBOTJR_SUBJECT_COMPATIBILITY: "FORWARD_TRANSITIVE"
  # Topic names
  SQRBOTJR_TOPIC_APP_MENTION: "sqrbot.app_mention"
  SQRBOTJR_TOPIC_MESSAGE_CHANNELS: "sqrbot.message.channels"
  SQRBOTJR_TOPIC_MESSAGE_IM: "sqrbot.message.im"
  SQRBOTJR_TOPIC_MESSAGE_GROUPS: "sqrbot.message.groups"
  SQRBOTJR_TOPIC_MESSAGE_MPIM: "sqrbot.message.mpim"
  SQRBOTJR_TOPIC_INTERACTION: "sqrbot.interaction"
  # Feature flags ("1"=enabled, "0"=disabled)
  SQRBOTJR_ENABLE_SCHEMAS: "1"
  SQRBOTJR_ENABLE_TOPIC_CONFIG: "1"
  SQRBOTJR_ENABLE_PRODUCERS: "1"
