apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqrbot
  labels:
    app: sqrbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqrbot
  template:
    metadata:
      labels:
        app: sqrbot
    spec:
      containers:
      - name: sqrbot-app
        image: lsstsqre/sqrbot-jr:0.5.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: sqrbot-app
        env:
        - name: SQRBOTJR_SLACK_SIGNING
          valueFrom:
            secretKeyRef:
              name: sqrbot
              key: SQRBOTJR_SLACK_SIGNING
        - name: SQRBOTJR_SLACK_TOKEN
          valueFrom:
            secretKeyRef:
              name: sqrbot
              key: SQRBOTJR_SLACK_TOKEN
        - name: SQRBOTJR_SLACK_APP_ID
          valueFrom:
            secretKeyRef:
              name: sqrbot
              key: SQRBOTJR_SLACK_APP_ID
        envFrom:
        - configMapRef:
            name: sqrbot
