sudo: required
dist: xenial
services:
  - docker
language: python
matrix:
  include:
    - python: "3.7.1"
      env: DEPLOY_DOCKER_IMAGE=true
install:
  - "make install"
script:
  - "make test"
  - "make image"
after_success:
  # Docker Hub (no-op for PRs and DEPLOY_DOCKER_IMAGE=false)
  - make travis-docker-deploy
env:
  global:
    - DEPLOY_DOCKER_IMAGE=false  # disable docker push in regular test matrix
    # DOCKER_USERNAME
    - secure: "g9ha3D9BdAiyRjaTQDH/LlNw8Hg6wG8DNaUB0a1rPrHNlu1Zydm5s4S+nDeUEKAstlbJqv0T6oNQHdTNr5++BL0JIB8Fyk18EM46gh6je0TnU+tQoN5sth9R8KhgHBJzQkLMrb7pbM/jL3wL7PKRLaLN9YuSF6uGxF3B6m5bM5mpVx2miawoZhYFc/PnnqCBiByj1WlP71HmTdiulX9VtmSuYYszDykwL88azpiFztEya8DDrKRTjV7FnaGoMgVM+frS9PDr/lMYy4Q8H0XT/Qz/THoxPx7J1bv5GstMyQ62Vk7CVN3MXMAtZX8zL4eIGW97/wHtzr/H93tMMicUE4q5UnnC0SMwy+rWRf3vhLGNJJbjUDV9lHzc8TbRMcAWxMEoP3BmKh2qRSGiGlV+KHyhb72cU5HYcfn76OyPJt9kUXOhjUZbjfoWQML3WbbC3TXbQnLuiDdeYdU4JiTeiPVTrvq4jIrg57OXfWzyVCeZxuDa4Oq5zL3/GQ/bhlbEzCh7+BplCZqaFFREOTsSwYtIVyjIAGXhW60kPMiSKKRQ+iZfjspUBhx1sdUtoYfPfQwAdZS00G9MKAguJs3v0TjPnCygvWKSzSMql87j8T4h8cyxzUiNrs8hhRIPTDzNZ+d6sqpNW40Dw4mLAP+PSBSGypWrjGT/Ehsj74iuyag="
    # DOCKER_PASSWORD
    - secure: "iWlNBl6f4DuQrBhyPyN/xXNQqK5CC+5kL9RckU/lGROusiBwCK2QRV/4acQZu44YKmVB351KYWNEgt7ewLNU7B7l6PqlJkoe6ph7GhzsVT8i/EVScB4TGPOnWVLi6xUiuH3woxE2Elrq8cTnezXspBITfPi9jeumKo16NRPySkPzCq2U6gKLQyCNdXLl6RZE2/76yfPTKGdW0POa+fXvprDomPKu02uf8cFI/SEtiMOEjyVBCVvqylyVZHBq4eGTdXQZAn5GJ4sDOeDXBtVVIF6zUG53zhpRYvNfRWzCRg82lzrey9gshP8hcremE/B3rslbI+BSFbqTk4etfae5IvmUtIXqv8cURSma+K4V0vme/2ttNZM4gZaCM6maoH4+J1UohOf+5uxvovjSMveyESZJO15OQEEnNbx0UotSL++d7Dr45WCGMEx7e/QY2527PkosyyRflNpyRR5kQZKalPiNyKQba8k3TrTYHiKCCmSEaB7rtZYRENlEBET//uKFsX5LY+9Gpn4bxjBjf3/UtA0IXCg/2fRZK+j6W/zjsAKaP81nqCSBflx2iZQdJOAl53ES4v2Nj8NkTQOh1Dp3PmMJYCFtmo2slX4FYp7qptHpail/MfuFxGBtkEa/HPWMj0ImyN5mizcPgdNK4ROfHyPdllJUf4DraJk8+LpdBBY="
