apiVersion: v1
kind: ConfigMap
metadata:
  name: sqrbot-jr
data:
  # These configurations are injected as environment variables into the
  # sqrbot-jr app container.
  API_LSST_CODES_PROFILE: "production"
