# Credentials for the @sqrbot-jr / SQuaRE Bot Jr Slack app. Any app in
# api.lsst.codes that needs to send Slack messages can use these credentials.
apiVersion: v1
kind: Secret
metadata:
  name: sqrbot-jr
type: Opaque
data:
  # echo -n '...' | base64
  # The Slack verification token (deprecated verification method)
  SQRBOTJR_SLACK_TOKEN: {{ SQRBOT_JR_SLACK_TOKEN }}
  # The Slack signing secret
  SQRBOTJR_SIGNING: {{ SQRBOTJR_SIGNING }}
